---
title: "Database"
output: html_document
date: "2024-03-05"
---


```{r}

library(RSQLite)
library(readr)

```


```{r}

# Connect to the database (this will create the database if it doesn't exist)

db_path = "/cloud/project/DATABASE/ecom.db"

db <- dbConnect(SQLite(), dbname = db_path)
 
# SQL commands to create the schema

sql_commands <- c(

  "DROP TABLE IF EXISTS advertisement;",

  "DROP TABLE IF EXISTS product_supplier;",

  "DROP TABLE IF EXISTS supplier;",

  "DROP TABLE IF EXISTS payment;",

  "DROP TABLE IF EXISTS order_details;",

  "DROP TABLE IF EXISTS customer;",

  "DROP TABLE IF EXISTS product;",

  "DROP TABLE IF EXISTS address;",

  "DROP TABLE IF EXISTS category;",

  "CREATE TABLE category (

    category_id INT PRIMARY KEY,

    category_name VARCHAR(255) NOT NULL,

    parent_category_id INT,

    category_description TEXT,

    FOREIGN KEY (parent_category_id) REFERENCES category(category_id)

  );",

  "CREATE TABLE address (

    address_id INT PRIMARY KEY,

    house_number INT NOT NULL,

    street VARCHAR(255) NOT NULL,

    city VARCHAR(100) NOT NULL,

    Post_Code VARCHAR(20) NOT NULL,

    country VARCHAR(100) NOT NULL

  );",

  "CREATE TABLE product (

    product_id INT PRIMARY KEY,

    product_name VARCHAR(255) NOT NULL,

    product_description TEXT,

    product_price DECIMAL(10, 2) NOT NULL,

    stockquantity INT NOT NULL,

    category_id INT,

    FOREIGN KEY (category_id) REFERENCES category(category_id)

  );",

  "CREATE TABLE customer (

    customer_id INT PRIMARY KEY,

    customer_email VARCHAR(255) NOT NULL,

    customer_phone VARCHAR(13) NOT NULL,

    first_name VARCHAR(100) NOT NULL,

    last_name VARCHAR(100) NOT NULL,

    password VARCHAR(255) NOT NULL,

    address_id INT,

    UNIQUE (customer_email),

    UNIQUE (customer_phone),

    FOREIGN KEY (address_id) REFERENCES address(address_id)

  );",

  "CREATE TABLE order_details (

    order_id INT PRIMARY KEY,

    customer_id INT,

    product_id INT,

    quantity INT NOT NULL,

    price DECIMAL(10, 2) NOT NULL,

    FOREIGN KEY (customer_id) REFERENCES customer(customer_id),

    FOREIGN KEY (product_id) REFERENCES product(product_id)

  );",

  "CREATE TABLE payment (

    payment_id INT PRIMARY KEY,

    customer_id INT,

    product_id INT,

    order_id INT,

    amount DECIMAL(10, 2) NOT NULL,

    payment_date DATE NOT NULL,

    payment_type VARCHAR(20) NOT NULL CHECK(payment_type IN('card', 'cash')),

    FOREIGN KEY (customer_id) REFERENCES customer(customer_id),

    FOREIGN KEY (order_id) REFERENCES order_details(order_id),

    FOREIGN KEY (product_id) REFERENCES product(product_id)

  );",

  "CREATE TABLE supplier (

    supplier_id INT PRIMARY KEY,

    supplier_name VARCHAR(255) NOT NULL,

    supplier_email VARCHAR(255),

    supplier_phone VARCHAR(20),

    address_id INT NOT NULL,

    UNIQUE (supplier_phone),

    FOREIGN KEY (address_id) REFERENCES address(address_id)

  );",

  "CREATE TABLE product_supplier (

    product_supplier_id INT PRIMARY KEY,

    product_id INT,

    supplier_id INT,

    supplier_price DECIMAL(10, 2) NOT NULL,

    supply_date DATE NOT NULL,

    FOREIGN KEY (product_id) REFERENCES product(product_id),

    FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id)

  );",

  "CREATE TABLE advertisement (

    ad_id VARCHAR(255) PRIMARY KEY,

    product_id INT,

    ad_url VARCHAR(255) NOT NULL,

    FOREIGN KEY (product_id) REFERENCES product(product_id)

  );"

)
 
# Execute each SQL command

for (sql in sql_commands) {

  dbExecute(db, sql)

}

# List of CSV files and their corresponding table names
files_and_tables <- list(
  "address.csv" = "address",
  "advertisement.csv" = "advertisement",
  "category.csv" = "category",
  "customer.csv" = "customer",
  "order_details.csv" = "order_details",
  "payment.csv" = "payment",
  "product_supplier.csv" = "product_supplier",
  "product.csv" = "product",
  "supplier.csv" = "supplier"
)
 
# Base path where CSV files are stored
base_path <- "/cloud/project/MOCKDATA/"

# Loop through each file and table name pair, import the CSV file into R, and then write to the SQLite table
for (file in names(files_and_tables)) {
  # Full path to the CSV file
  file_path <- paste0(base_path, file)
  # Read the CSV file into a data frame
  data_frame <- read_csv(file_path)
  # Write the data frame to the SQLite table
  # This assumes table names and CSV file column names match the database schema
  dbWriteTable(db, files_and_tables[[file]], data_frame, append = TRUE, row.names = FALSE)
}



# Disconnect from the database

# dbDisconnect(db)


```

```{sql connection=db}

SELECT *
FROM product

```


